### ISSUE TITLE
This is too good!

### ISSUE THREAD

**Issue by pskl** [jasonwebb/morphogenesis-resources#2]
self explanatory

**Comment by nukadelic** [comment]
Agreed, i have tried / seen about third of the items in the list, but never knew what it was. The closest i have found was the term "generative algorithms"

**Comment by jasonwebb** [comment]
Thank you both! 

@nukadelic - I also struggle finding exactly what I have in mind on this topic, and find that terms vary based on the perspective of the industry, field, or community particular literature and work comes from. Personally I come from a creative coding and digital fabrication mindset, so I'm very focused on computational perspectives, VFX tools, and visual art on Twitter, IG, and elsewhere. But someone from an architectural background or academia might be used to seeing some of the terms used a little differently. For instance, the term "morphogenesis" has a pretty specific use in cell biology to describe the process of cell differentiation and specialization. I'd like to think I'm using the term "digital morphogenesis" more holistically and literally, even encompassing those more field-specific definitions. But as with anything involving technology and research, terms can evolve!

**Comment by nukadelic** [comment]
@jasonwebb well i did look for the biological morphogenesis images on google and ended here by accident. I think this needs to be a website to allow users submit more ideas like the excellent wave function collapse by mag , could be neat if a demo link to codepen or jsdille is also provided

**Comment by jasonwebb** [comment]
Actually, that kind of collaboration is part of why I chose to put it on Github! I am absolutely open to taking pull requests (like @Gargaj did earlier today here: https://github.com/jasonwebb/morphogenesis-resources/pull/3). If working with Git, forks, PRs, etc is not your thing, I would definitely welcome you to just open an Issue with any info you'd like to see added or changed (CodePen/JSFiddle examples, cool relevant projects, etc) and I will integrate it and let you know when its done!
