### ISSUE TITLE
Book Recommendation: The Algorithmic Beauty of Sea Shells

### ISSUE THREAD

**Issue by JohnGemstone** [jasonwebb/morphogenesis-resources#29]
Just dropping a recommendation for the books list:
_The Algorithmic Beauty of Sea Shells by Hans Meinhardt_
[Amazon link to book](https://www.amazon.com/Algorithmic-Beauty-Shells-Virtual-Laboratory/dp/3540921419/)

I remember it being referenced in one of Philip Ball's books. It's part of a series called 'The Virtual Laboratory' by publish Springer which cover a few other patterns (which I have yet to read/recommend):
[The Virtual Laboratory series on Springer](https://www.springer.com/series/1361)

Thanks for putting these lists together, I have been making my own but this is far more complete.

**Comment by jasonwebb** [comment]
Thanks @JohnGemstone! I've added a reference to it in the [Books](https://github.com/jasonwebb/morphogenesis-resources/blob/master/README.md#books) section.
