### ISSUE TITLE
(recommendation) Dithering

### ISSUE THREAD

**Issue by emoc** [jasonwebb/morphogenesis-resources#30]
An online application to dither small images and prepare machine knitting files, with realtime parameters. I tried to add as much dithering algorithms as I was able to find! 
Main version is written in p5.js, from a prior version in Processing. 
app : http://lesporteslogiques.net/tricot-machine/tramage/ 
code : https://github.com/lesporteslogiques/tricot-machine

**Comment by jasonwebb** [comment]
Awesome, thanks! And thanks for making it open source! :) Added it to the README in the commit above. Please let me know if there is anything you'd like to change in the reference.
