### ISSUE TITLE
Add Scrawl-canvas Javascript library to the 'Languages and frameworks' section at the bottom of the page

### ISSUE THREAD

**Issue by KaliedaRik** [jasonwebb/morphogenesis-resources#33]
Hi Jason,

Grateful if you would consider adding my Javascript canvas library - Scrawl-canvas[1] - as a link in the 'Languages and frameworks' section at the bottom of the page.

[1] link: https://scrawl-v8.rikweb.org.uk/

**Why?**
Scrawl-canvas is a fast and efficient library for creating 2D <canvas> animations, infographics and other graphical representations for websites.

**Yes, but why add it to this resources page?**
Scrawl-canvas comes with some morphogenesis resources already built-in - mainly because they are really useful for making patterns, backgrounds and other visual effects as a part of an infographic or animation. For example:

- The Scrawl-canvas noise asset has Perlin, Simplex, Value and Worley noise engines built-in. The Perlin, Simplex and Value noise generator code is based on code found in the [canvas-noise GitHub repository](https://github.com/lencinhaus/canvas-noise) written by [lencinhaus](https://github.com/lencinhaus). The Worley functionality builds on code found in the [jackunion/tooloud GitHub repository](https://github.com/jackunion/tooloud/blob/master/src/Worley.js). See Scrawl-canvas demo at https://scrawl-v8.rikweb.org.uk/demo/filters-019.html
- Scrawl-canvas also includes a reaction-diffusion asset, inspired by your (ie: Jason Webb's) [Reaction-Diffusion Playground](https://jasonwebb.github.io/reaction-diffusion-playground/). This code runs entirely in 2D canvas, without recourse to WebGL, Wasm, web workers, etc. See Scrawl-canvas demo at https://scrawl-v8.rikweb.org.uk/demo/canvas-053.html
- While Scrawl-canvas doesn't have a complete physics engine, it does include a particles engine. See the [Scrawl-canvas demo index page](https://scrawl-v8.rikweb.org.uk/demonstrations) for a list of particle-related demos.

Scrawl-canvas also makes an effort to play nicely with third party libraries - for instance the [Delaunator](https://github.com/mapbox/delaunator) JavaScript library for Delaunay triangulation of 2D points - example at https://scrawl-v8.rikweb.org.uk/demo/delaunator-001.html

**Comment by jasonwebb** [comment]
Sure thing - done!
