### ISSUE TITLE
Recommendation for new Physarum interactive explainer resource

### ISSUE THREAD

**Issue by golanlevin** [jasonwebb/morphogenesis-resources#45]
Hi Jason, 
@DenizBicer has made a lovely [interactive explainer](https://denizbicer.com/202408-UnderstandingPhysarum.html) for the Physarum simulation. I nominate it for inclusion under *Physarum/Articles*: 

> https://denizbicer.com/202408-UnderstandingPhysarum.html

<img width="515" alt="Screenshot 2024-08-07 at 5 01 28 PM" src="https://github.com/user-attachments/assets/c9727413-85f0-4608-98c3-51a6a64dbdf7">

best,
@golanlevin

**Comment by jasonwebb** [comment]
Thanks @golanlevin! I just saw this again in the Gorilla Sun newsletter, and I totally agree it should be added. The explainer helped me understand the algorithm finally, so I added a general description along with the links. 

https://github.com/jasonwebb/morphogenesis-resources?tab=readme-ov-file#physarum

**Comment by DenizBicer** [comment]
It makes me happy to read that it helped you understand the algorithm. Thank you for including the explainer in the list!
